# Generated by Django 5.2.6 on 2025-09-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverification_resetpasswordvaluationtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='otp',
            field=models.IntegerField(max_length=6),
        ),
    ]
